### PR TITLE
106 milestone 1a

### PR DESCRIPTION
**Pull request by psiotwo**
**DO NOT MERGE YET - REQUIRES SSP LAYOUT CHANGE**

@karelklima @bindeali 

- draft implementation of publishing assets to GIT
- changing the layout of the GIT repository - vocabularies will be published flat in the `/content/vocabularies` folder. The new one is: 
`/content/vocabularies/<VOC_ID>`
`/content/assets/<ASSET_ID>`
- changed the PR text to reflect also the changed assets
- there is currently no link between a vocabulary and an asset. Can be added. But maybe a better way would be to resolve the relevant diagrams by the client (OntoGrapher) dynamically based on the used terms. Discussion welcome.
- what still needs to be updated is the publication script of SSP to Virtuoso.

Sample:
- example data for publishing: https://xn--slovnk-test-scb.mvcr.gov.cz/modelujeme/sluzby/db-server/resource?uri=https:%2F%2Fslovn%C3%ADk.gov.cz%2Fdatov%C3%BD%2Fpracovn%C3%AD-prostor%2Fpojem%2Fmetadatov%C3%BD-kontext%2Finstance1546316314&role=context
- example PR created by the publishing logic:  https://github.com/opendata-mvcr/ssp/pull/310

### CODE REVIEW

**Comment by psiotwo** [comment]
Thanks for feedback. 

I agree that some form of explicit index from vocabularies to assets should be present for performance reasons. I am a bit unsure about having users select it on their own - it seems to me that it is another possible point of inconsistency, because the users might not do it properly (since the information is already there from their PoV). 

So, next bit of brainstorming:
1) Each app will use some API (SGoV/SPARQL) to augment the metadata context with links from vocabularies to assets (e.g. OntoGrapher will add a triple <VOC> has <ASSET> to the metadata context, either through SGoV or through SPARQL whenever the user adds a diagram to the workspace)
2) SGoV server will add link assets in the workspace to all vocabularies in the workspace
3) SGoV server will scan all asset contexts to get all asset-vocabulary links based on a predefined RDF property.

For 1,2,3 Then, SGoV server creates a new TTL file in GitHub - assets.ttl - that will contain links from the given vocabulary to the assets.

4) The links will be computed (and materialized) in the triple store by means of some rules.

**Comment by karelklima** [comment]
>  I am a bit unsure about having users select it on their own - it seems to me that it is another possible point of inconsistency, because the users might not do it properly (since the information is already there from their PoV).

I agree completely. It is one more (unnecessary) step to confuse users.

From the user's point of view, when operating with OntoGrapher specifically, it would be great to auto-assign diagrams to relevant vocabularies that are added to the workspace (i.e. write only!). So what if the diagram uses term `X` from vocabulary `A`, OntoGrapher would link this asset to vocabulary `A`. If the diagram uses terms from vocabularies `A` and `B`, then OntoGrapher would link the asset to both vocabularies.

As of how to do it within the data architecture - I think that adding explicit links somewhere in the metadata context is OK, and letting apps create those links via SPARQL is OK as well - unless we want the metadata context to be managed exclusively by the API, but in that case we would let the API create application contexts as well (to be consistent).

**Comment by psiotwo** [comment]
Extended with the publication of "<VOC>-přílohy.ttl" file along with glosář/model/slovník. 

Sample:

example data for publishing: https://xn--slovnk-test-scb.mvcr.gov.cz/modelujeme/sluzby/db-server/resource?uri=https:%2F%2Fslovn%C3%ADk.gov.cz%2Fdatov%C3%BD%2Fpracovn%C3%AD-prostor%2Fpojem%2Fmetadatov%C3%BD-kontext%2Finstance1546316314&role=context

example PR created by the publishing logic: https://github.com/opendata-mvcr/ssp/pull/312

**Review by karelklima — APPROVED** [review]
LGTM

**Review by karelklima — DISMISSED** [review]

**Pull request merged**
